IF DB_ID('SQLTrainer_ECommerce') IS NOT NULL
BEGIN
    ALTER DATABASE SQLTrainer_ECommerce SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SQLTrainer_ECommerce;
END;
GO
CREATE DATABASE SQLTrainer_ECommerce;
GO
USE SQLTrainer_ECommerce;
GO
